steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/aibat-c447f/aibat-frontend", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/aibat-c447f/aibat-frontend"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "aibat-frontend",
        "--image",
        "gcr.io/aibat-c447f/aibat-frontend",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
